//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int comment_ID { get; set; }
        public string text { get; set; }
        public string date { get; set; }
        public Nullable<int> creator_ID { get; set; }
        public Nullable<int> question_ID { get; set; }
        public Nullable<int> answer_ID { get; set; }
        public Nullable<int> journey_ID { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual Question Question { get; set; }
        public virtual Journey Journey { get; set; }
    }
}
