//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class savedQuestion
    {
        public int savedQuestions_ID { get; set; }
        public Nullable<int> creator_ID { get; set; }
        public Nullable<int> question_ID { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Question Question { get; set; }
    }
}
