//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StackOverFlow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uni_fact_branch
    {
        public Nullable<int> university_ID { get; set; }
        public Nullable<int> branch_ID { get; set; }
        public Nullable<int> factulty_ID { get; set; }
        public int id { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Factulty Factulty { get; set; }
        public virtual University University { get; set; }
    }
}
